sonar.projectKey=msi-python-project-50
sonar.organization=painkiller2001
sonar.host.url=https://sonarcloud.io
sonar.python.coverage.reportPaths=/github/workspace/coverage.xml
sonar.sources=gen_diff
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
