name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest pytest-cov
        pip install -e .

    - name: Lint with ruff
      run: |
        ruff --version
        ruff check .

    - name: Run tests with coverage
      run: |
        pytest --cov=gendiff --cov-report=xml:coverage.xml tests/

    - name: Fix coverage paths for SonarCloud
      run: |
        sed -i 's|/home/runner/work/python-project-50/python-project-50/||g' coverage.xml
    
    - name: Upload coverage report (for debugging)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml
        path: coverage.xml
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_SECRET_KEY }}